// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AccessControlUpgradeable$Type } from "./AccessControlUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AccessControlUpgradeable"]: AccessControlUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol:AccessControlUpgradeable"]: AccessControlUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["AccessControlUpgradeable"]: GetContractReturnType<AccessControlUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol:AccessControlUpgradeable"]: GetContractReturnType<AccessControlUpgradeable$Type["abi"]>;
  }
}
