// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC165Upgradeable$Type } from "./ERC165Upgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC165Upgradeable"]: ERC165Upgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/utils/introspection/ERC165Upgradeable.sol:ERC165Upgradeable"]: ERC165Upgradeable$Type;
  }

  interface ContractTypesMap {
    ["ERC165Upgradeable"]: GetContractReturnType<ERC165Upgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/utils/introspection/ERC165Upgradeable.sol:ERC165Upgradeable"]: GetContractReturnType<ERC165Upgradeable$Type["abi"]>;
  }
}
