// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RccToken$Type } from "./RccToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RccToken"]: RccToken$Type;
    ["contracts/rcc.sol:RccToken"]: RccToken$Type;
  }

  interface ContractTypesMap {
    ["RccToken"]: GetContractReturnType<RccToken$Type["abi"]>;
    ["contracts/rcc.sol:RccToken"]: GetContractReturnType<RccToken$Type["abi"]>;
  }
}
