// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RCCStake$Type } from "./RCCStake";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RCCStake"]: RCCStake$Type;
    ["contracts/rcc-stake.sol:RCCStake"]: RCCStake$Type;
  }

  interface ContractTypesMap {
    ["RCCStake"]: GetContractReturnType<RCCStake$Type["abi"]>;
    ["contracts/rcc-stake.sol:RCCStake"]: GetContractReturnType<RCCStake$Type["abi"]>;
  }
}
