// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PausableUpgradeable$Type } from "./PausableUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PausableUpgradeable"]: PausableUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/utils/PausableUpgradeable.sol:PausableUpgradeable"]: PausableUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["PausableUpgradeable"]: GetContractReturnType<PausableUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/utils/PausableUpgradeable.sol:PausableUpgradeable"]: GetContractReturnType<PausableUpgradeable$Type["abi"]>;
  }
}
