// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RCCStakeLib$Type } from "./RCCStakeLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RCCStakeLib"]: RCCStakeLib$Type;
    ["contracts/RCCStakeLib.sol:RCCStakeLib"]: RCCStakeLib$Type;
  }

  interface ContractTypesMap {
    ["RCCStakeLib"]: GetContractReturnType<RCCStakeLib$Type["abi"]>;
    ["contracts/RCCStakeLib.sol:RCCStakeLib"]: GetContractReturnType<RCCStakeLib$Type["abi"]>;
  }
}
