// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface RCCStakeLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "RCCStakeLib",
  "sourceName": "contracts/RCCStakeLib.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220cb68f121fb476d8128b8d0eef74f295b54716e570a899e30fd1fdda8f11d847664736f6c63430008160033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220cb68f121fb476d8128b8d0eef74f295b54716e570a899e30fd1fdda8f11d847664736f6c63430008160033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "RCCStakeLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RCCStakeLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/RCCStakeLib.sol:RCCStakeLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RCCStakeLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "RCCStakeLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RCCStakeLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/RCCStakeLib.sol:RCCStakeLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RCCStakeLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "RCCStakeLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RCCStakeLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/RCCStakeLib.sol:RCCStakeLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RCCStakeLib$Type["abi"]>>;
}
