import '../styles/globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from '@mui/material/styles';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { config } from '../utils/wagmi';
import theme from '../utils/theme';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import Layout from '../components/layout';

const client = new QueryClient();

/**
 * _app.tsx 是一个自定义的 App 组件，用于覆盖 Next.js 内置的 App 组件。它可以让你在所有页面间共享布局或状态。
 *
 * 你可以在此文件中添加全局样式、提供上下文 Providers 或其他在所有页面共享的逻辑。
 */

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Rcc Stake</title>
        <meta content='Generated by @rainbow-me/create-rainbowkit' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <ThemeProvider theme={theme}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={client}>
            <RainbowKitProvider>
              <ToastContainer
                position='top-right'
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme='light'
              />
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
